version: '3.8'

services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:13
    container_name: tofumaker-postgres-staging
    environment:
      POSTGRES_DB: tofumaker_staging
      POSTGRES_USER: tofumaker_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data
      - ./backend/src/main/resources/db/migration:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - tofumaker-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tofumaker_user -d tofumaker_staging"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis 캐시
  redis:
    image: redis:7-alpine
    container_name: tofumaker-redis-staging
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6380:6379"
    volumes:
      - redis_data_staging:/data
    networks:
      - tofumaker-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 백엔드 애플리케이션
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY}-backend:${IMAGE_TAG:-latest}
    container_name: tofumaker-backend-staging
    environment:
      SPRING_PROFILES_ACTIVE: staging
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tofumaker_staging
      SPRING_DATASOURCE_USERNAME: tofumaker_user
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: ${REDIS_PASSWORD}
      OPENSTACK_AUTH_URL: ${OPENSTACK_AUTH_URL}
      OPENSTACK_USERNAME: ${OPENSTACK_USERNAME}
      OPENSTACK_PASSWORD: ${OPENSTACK_PASSWORD}
      OPENSTACK_PROJECT_NAME: ${OPENSTACK_PROJECT_NAME}
      OPENSTACK_USER_DOMAIN_NAME: ${OPENSTACK_USER_DOMAIN_NAME}
      OPENSTACK_PROJECT_DOMAIN_NAME: ${OPENSTACK_PROJECT_DOMAIN_NAME}
      JWT_SECRET: ${JWT_SECRET}
      LOG_LEVEL: INFO
    ports:
      - "8082:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - tofumaker-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # 프론트엔드 애플리케이션
  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY}-frontend:${IMAGE_TAG:-latest}
    container_name: tofumaker-frontend-staging
    environment:
      REACT_APP_API_URL: http://backend:8080/api
      REACT_APP_ENVIRONMENT: staging
    ports:
      - "81:80"
    depends_on:
      - backend
    networks:
      - tofumaker-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data_staging:
    driver: local
  redis_data_staging:
    driver: local

networks:
  tofumaker-network:
    driver: bridge 