server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: boardstack
  
  profiles:
    active: dev
    
  # JPA & Database 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/boardstack
    username: boardstack_user
    password: boardstack_pass
    driver-class-name: org.postgresql.Driver
    
    # HikariCP 연결 풀 설정
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  
  h2:
    console:
      enabled: true
      path: /h2-console
      
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate  # Flyway를 사용하므로 validate로 설정
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  
  # Flyway 마이그레이션 설정
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true

# 로깅 설정
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core: DEBUG
    com.example.boardstack: DEBUG

# JWT 설정
jwt:
  secret: myVerySecretKeyForJWTTokenGenerationAndValidation2024!
  expiration: 86400000  # 24시간 (밀리초)
  refresh-expiration: 604800000  # 7일 (밀리초)

# 애플리케이션 커스텀 설정
app:
  name: BoardStack Application
  version: 0.0.1-SNAPSHOT
  description: Spring Boot + OpenStack Integration System
  
# OpenStack 연동 설정
openstack:
  tofumaker:
    base-url: http://localhost:8080/api/v1
    timeout: 30000
    enabled: false
  templates:
    base-path: classpath:/terraform/
    
# HTTP 클라이언트 설정
http:
  client:
    connection-timeout: 5000
    read-timeout: 30000
    max-connections: 100

# Swagger/OpenAPI 설정
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

---
# 개발 환경 설정
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop

---
# 테스트 환경 설정
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop 