spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/tofumaker_staging
    username: tofumaker_user
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      validation-timeout: 5000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  
  redis:
    host: redis
    port: 6379
    password: ${REDIS_PASSWORD}
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  
  # 캐시 설정
  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10분
  
  # 로깅 설정
  logging:
    level:
      com.tofumaker: INFO
      org.springframework.security: WARN
      org.hibernate.SQL: WARN
      org.hibernate.type.descriptor.sql.BasicBinder: WARN
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file:
      name: /var/log/tofumaker/application.log
      max-size: 100MB
      max-history: 30

# 액추에이터 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# OpenStack 설정
openstack:
  auth-url: ${OPENSTACK_AUTH_URL}
  username: ${OPENSTACK_USERNAME}
  password: ${OPENSTACK_PASSWORD}
  project-name: ${OPENSTACK_PROJECT_NAME}
  user-domain-name: ${OPENSTACK_USER_DOMAIN_NAME}
  project-domain-name: ${OPENSTACK_PROJECT_DOMAIN_NAME}

# JWT 설정
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000  # 24시간

# 애플리케이션 설정
app:
  environment: staging
  cors:
    allowed-origins: 
      - "http://localhost:81"
      - "https://staging.tofumaker.com"
  upload:
    max-file-size: 10MB
    max-request-size: 50MB 